<a href="https://colab.research.google.com/github/19PA1AO5C4/Tensorflow/blob/main/Q1.Tensor%20Manipulations%20%26%20Reshaping.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf

# 1. Create a random tensor of shape (4, 6)
tensor = tf.random.normal(shape=(4, 6))

# 2. Find its rank and shape using TensorFlow functions.
rank_before = tf.rank(tensor)
shape_before = tf.shape(tensor)

print("Original Tensor:")
print(tensor)
print("Rank before reshaping:", rank_before.numpy())
print("Shape before reshaping:", shape_before.numpy())

# 3. Reshape it into (2, 3, 4) and transpose it to (3, 2, 4).
reshaped_tensor = tf.reshape(tensor, (2, 3, 4))
transposed_tensor = tf.transpose(reshaped_tensor, perm=[1, 0, 2])  # Note the permutation for transpose

rank_after_reshape = tf.rank(reshaped_tensor)
shape_after_reshape = tf.shape(reshaped_tensor)

rank_after_transpose = tf.rank(transposed_tensor)
shape_after_transpose = tf.shape(transposed_tensor)


print("\nReshaped Tensor:")
print(reshaped_tensor)
print("Rank after reshaping:", rank_after_reshape.numpy())
print("Shape after reshaping:", shape_after_reshape.numpy())

print("\nTransposed Tensor:")
print(transposed_tensor)
print("Rank after transposing:", rank_after_transpose.numpy())
print("Shape after transposing:", shape_after_transpose.numpy())



# 4. Broadcast a smaller tensor (1, 4) to match the larger tensor and add them.
smaller_tensor = tf.random.normal(shape=(1, 4))

# Broadcasting happens implicitly during the addition.  No explicit broadcast needed.
broadcasted_sum = transposed_tensor + smaller_tensor

print("\nResult after broadcasting and addition:")
print(broadcasted_sum)


# 5. Explain how broadcasting works in TensorFlow.
print("\nExplanation of Broadcasting:")
print("""
Broadcasting in TensorFlow (and NumPy) allows arithmetic operations between tensors of different shapes,
as long as certain compatibility rules are met.  It avoids explicit data replication, making operations
more memory and computationally efficient.

In this example, 'smaller_tensor' with shape (1, 4) is added to 'transposed_tensor' with shape (3, 2, 4).
Broadcasting works as follows:

1. **Dimension Alignment:** TensorFlow compares the shapes of the two tensors dimension by dimension, starting from the trailing dimensions (rightmost).

2. **Compatibility Rules:** Two dimensions are compatible if:
   a) They are equal, or
   b) One of them is 1.

3. **Expansion:**  If a dimension in one tensor is 1, TensorFlow "stretches" or "copies" that dimension to match the corresponding dimension in the other tensor.  This is the "broadcasting" part.

In our case:
- (3, 2, 4) and (1, 4)

- The last dimension (4) matches.
- The second to last dimension: 2 vs 1. The 1 is broadcasted to 2.
- The first dimension: 3 vs nothing (implicitly 1). The 1 is broadcasted to 3.

So, the (1,4) tensor is effectively "expanded" to (3, 2, 4) by replicating its rows and then the element-wise addition is performed.

Broadcasting simplifies code and improves performance, but it's crucial to understand how it works to avoid unexpected results.  If shapes are not compatible for broadcasting, TensorFlow will raise an error.
""")

Original Tensor:
tf.Tensor(
[[-0.22058809  0.82398534  0.4602762   0.22344792  0.9093572  -1.7552847 ]
 [-1.9654704   0.31234542 -0.02235971 -0.7876967   0.02119053  0.89816743]
 [ 1.343661    0.91865844  0.5340491   1.7817957   0.09752576  0.24681519]
 [ 1.4762636  -0.60604674  1.2595838  -0.21459451 -1.6049099  -0.92720926]], shape=(4, 6), dtype=float32)
Rank before reshaping: 2
Shape before reshaping: [4 6]

Reshaped Tensor:
tf.Tensor(
[[[-0.22058809  0.82398534  0.4602762   0.22344792]
  [ 0.9093572  -1.7552847  -1.9654704   0.31234542]
  [-0.02235971 -0.7876967   0.02119053  0.89816743]]

 [[ 1.343661    0.91865844  0.5340491   1.7817957 ]
  [ 0.09752576  0.24681519  1.4762636  -0.60604674]
  [ 1.2595838  -0.21459451 -1.6049099  -0.92720926]]], shape=(2, 3, 4), dtype=float32)
Rank after reshaping: 3
Shape after reshaping: [2 3 4]

Transposed Tensor:
tf.Tensor(
[[[-0.22058809  0.82398534  0.4602762   0.22344792]
  [ 1.343661    0.91865844  0.5340491   1.7817957 ]]

 [[ 0.9093572  -